logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.netflix: INFO
    org.springframework.security: INFO
    org.springframework.cloud: INFO
    org.springframework.boot: INFO
    io.netty: ERROR
    reactor.ipc: ERROR
    com.spring.webflux: ERROR    
      