server:
  port: 8083
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.netflix: INFO
    org.springframework.security: INFO
    org.springframework.cloud: INFO
    org.springframework.boot: INFO
    io.netty: ERROR
    reactor.ipc: ERROR
    reactor: ERROR
    com.spring.webflux: INFO
    org.springframework.web.reactive: ERROR